# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main
- features/*


# pool:
#   vmImage: 'ubuntu-latest'
pool: localMachine


variables:
  solution: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: verification
    jobs:
    - job: linux_verify
      timeoutInMinutes: 10
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: DotNetCoreCLI@2
        name: Restore
        inputs:
          command: 'restore'
          projects: '$(solution)'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        name: Build
        inputs:
          command: 'build'
          projects: '$(solution)'
          arguments: '-c $(buildConfiguration)'

    - job: win_verify
      timeoutInMinutes: 10
      pool: localmachine
      steps:
      - task: DotNetCoreCLI@2
        name: Restore
        inputs:
          command: 'restore'
          projects: '$(solution)'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        name: Build
        inputs:
          command: 'build'
          projects: '$(solution)'
          arguments: '-c $(buildConfiguration)'


    - job: generate_linux_artifacts
      timeoutInMinutes: 10
      pool:
        vmImage: 'ubuntu-latest'
      dependsOn: [linux_verify, win_verify]
      steps:
      - task: DotNetCoreCLI@2
        name: Restore
        inputs:
          command: 'restore'
          projects: '$(solution)'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: "Publishing"
        inputs:
          command: "publish"
          projects: '$(solution)'
          publishWebProjects: true
          arguments: "-o $(Build.ArtifactStagingDirectory)"

      - task: DotNetCoreCLI@2
        name: Test
        inputs:
          command: 'test'
          projects: '$(solution)'

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: WebApp